config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"

  resources :towns, only: [] do
    resources :events, only: :index, module: :towns
  end

  resources :events, only: %i[show index]
  resources :discussions, only: :show do
    resources :comments, only: :create, module: :discussions
  end
  resources :filters, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :discussion
  has_one :event, through: :discussion
  has_one :topic, through: :discussion

  validates :user, :text, :discussion, presence: true

  delegate :full_name, to: :user, prefix: true
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :event
  belongs_to :topic

  has_many :comments, dependent: :destroy

  delegate :name, to: :topic, prefix: true
end

app/models/discussion_topic.rb
class DiscussionTopic < ApplicationRecord
  has_many :discussions
  has_many :events, through: :discussions

  validates :name, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :starts_at, :ends_at, :title, presence: true

  belongs_to :town
  has_many :discussions, dependent: :destroy
  has_many :topics, through: :discussions
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :town, optional: true
  belongs_to :topic, optional: true
  belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :discussions
  has_many :events, through: :discussions

  validates :name, presence: true
end

app/models/town.rb
class Town < ApplicationRecord
  validates :name, presence: true

  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :full_name, presence: true

  has_many :comments
  has_many :filters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization
  include BulletHelper

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

app/controllers/concerns/bullet_helper.rb
module BulletHelper
  def skip_bullet
    return unless defined?(Bullet)
    return unless Bullet.enable?

    # Can't use `Bullet.enable=` b/c it's resets settings
    # https://github.com/flyerhzm/bullet/blob/master/lib/bullet.rb#L48-L58
    Bullet.instance_variable_set :@enable, false

    yield
  ensure
    Bullet.instance_variable_set :@enable, true
  end
end

app/controllers/discussions/comments_controller.rb
module Discussions
  class CommentsController < ApplicationController
    expose :discussion
    expose :comment, parent: :discussion

    def create
      comment.save
      respond_with comment, location: discussion_path(discussion)
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
            .merge(user: current_user)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  expose :discussion
  expose :comments, -> { discussion.comments.includes(:user) }

  def show
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  expose :events, :fetch_events

  expose :event
  expose :discussions, -> { event.discussions.includes(:topic) }
  expose :filter, id: -> { params[:filter_id] || params[:filter] && params[:filter][:id] }

  def show
  end

  def index
  end

  private

  def fetch_events
    if params[:filter].present?
      filter.new_record? && self.filter = Filter.new(filter_params)

      Events::FilteredQuery.new(filter: filter).all
    else
      Event.all
    end
  end

  def filter_params
    params[:filter].permit(:town_id, :topic_id, :max_starts_at, :min_starts_at)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  expose :filter, parent: :current_user

  def create
    filter.save
    respond_with filter, location: events_path(filter_id: filter.id)
  end

  private

  def filter_params
    params.require(:filter).permit(
      :town_id,
      :name,
      :topic_id,
      :max_starts_at,
      :min_starts_at
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/towns/events_controller.rb
module Towns
  class EventsController < ApplicationController
    expose :towns
    expose :town
    expose :events, from: :town
    expose :filter, id: :filter_id

    def index
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    def update_resource(resource, params)
      resource.update_attributes(params)
    end

    def account_update_params
      params = devise_parameter_sanitizer.sanitize(:account_update)

      if passwords_blank?(params)
        params.except(:password, :password_confirmation)
      else
        params
      end
    end

    def passwords_blank?(params)
      params[:password].blank? && params[:password_confirmation].blank?
    end
  end
end

app/views/application/_event_filter.html.slim
= simple_form_for filter, url: events_path, method: :post, html: { class: "js-filter-form" } do |f|
  = radio_button_tag "filter_type", "apply", true, id: "js-apply-filter",
    data: { url: events_path, method: "get" }
  = label_tag "js-apply-filter", "Apply Filter"

  = radio_button_tag "filter_type", "save", false, id: "js-save-filter",
    data: { url: filters_path, method: "post" }
  = label_tag "js-save-filter", "Save Filter"

  = radio_button_tag "filter_type", "load", false, id: "js-load-filter",
    data: { url: events_path, method: "get" }
  = label_tag "js-load-filter", "Load Filter"

  = f.input :name, label: "Filter Name", disabled: true,
    input_html: { id: "js-filter-name" }

  = label_tag "js-select-filter", "Select Existing Filter"
  = f.select :id,
    current_user.filters.collect { |f| [f.name, f.id] },
    { include_blank: false },
    { id: "js-select-filter" }

  #js-filter-fields
    = f.association :town, label_method: :name
    = f.association :topic, label_method: :name
    = f.input :min_starts_at
    = f.input :max_starts_at

  = f.submit "Apply Filter"

app/views/application/_footer.html.slim
footer.row
  .columns
    p &copy; Flatstack #{Time.zone.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.title-bar data-hide-for="medium" data-responsive-toggle="navigation_menu"
  button.menu-icon data-toggle="" type="button"
  title-bar-title Menu

nav.top-bar#navigation_menu
  = render "navigation_main"
  = render "navigation_user"

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    li = link_to "Rails Base example site", root_path
    - if user_signed_in?
      = active_link_to "Home", root_path, active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if user_signed_in?
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Edit profile", edit_user_registration_path
        li = link_to "Sign out", destroy_user_session_path
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

app/views/discussions/show.html.slim
.row
  .columns
    h2 = discussion.topic_name

    - comments.each do |comment|
      p = comment.user_full_name
      p = comment.text
      br

    = simple_form_for :comment, url: discussion_comments_path(discussion) do |f|
      = f.input :text
      = f.button :submit

app/views/events/index.html.slim
.row
  .columns
    h2 All events

    - events.each do |event|
      p = event.title
      p = event.description
      br

    = render "event_filter"

app/views/events/show.html.slim
.row
  .columns
    h2 = event.title
    p = event.description

    - discussions.each do |discussion|
      p = discussion.topic_name
      br

app/views/events/topics/show.html.slim
.row
  .columns
    h2 = topic.name

    - comments.each do |comment|
      p = comment.user_full_name
      p = comment.text
      br

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = display_meta_tags site: "RailsBase", keywords: %w(title site)
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_tag "window.App = {}"

    == analytics_init if GoogleAnalytics.valid_tracker?

  body
    = render "navigation"
    = render "messages"

    main.container
      = yield

    = render "footer"

    javascript:
      App.currentUserData = #{{current_user.to_json}};

    = javascript_include_tag :application

app/views/pages/home.html.slim
.row
  .columns
    h2
      = title("Home")

app/views/towns/events/index.html.slim
.row
  .columns
    h2 #{town.name} events

    - events.each do |event|
      p = event.title
      p = event.description
      br

    = render "event_filter"

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.no-bullet
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)